apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-first-rs
  labels:
    version: 0.0.1
spec:
  replicas: 2
  selector:
    matchLabels:
      project: my-Project
  template:
    metadata:
      labels:
        project: my-Project
    spec:
      containers:
      - name: my-pods-for-rs
        image: nginx
        ports:
        - containerPort: 80